# Reload the file with Prefix r
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# Splitting panes
bind | split-window -h
bind - split-window -v
# unbind '"'
# unbind %

# Set the base index for windows to 1 instead of 0.
set -g base-index 1

# Set the base index for panes to 1 instead of 0.
setw -g pane-base-index 1

# Don't rename windows automatically (use , to rename windows btw)
set-option -g allow-rename off

# Bind the arrows to pane switching without the -r argument so that
# repeated key presses aren't expected
# This prevents annoying behaviour where the next key press after switching panes with
# the arrow keys is interpreted as a command
bind-key Up    select-pane -U
bind-key Down  select-pane -D
bind-key Left  select-pane -L
bind-key Right select-pane -R

##############
# MOUSE MODE #
##############
set -g mouse on
set -g word-separators "\"'()[]{}<>,;|="
unbind-key -n C-MouseDown1Pane
unbind-key -n C-MouseDown2Pane
unbind-key -n M-MouseDown1Pane
unbind-key -n M-MouseDown2Pane
bind-key -n M-MouseDown1Pane run-shell \
    "tmux display-popup -E -d '#{pane_current_path}' '$EDITOR #{q:mouse_word}'"

#########
# SHELL #
#########
set-option -g default-shell /ws/olijohns-sjc/bin/fish

######################
# ITERM2 INTEGRATION #
######################
set -g allow-passthrough on

##################
# DESIGN CHANGES #
##################
# Status line transparent
set -g status-style bg=default

#######
# TPM #
#######
# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Dracula plugin
set -g @plugin 'dracula/tmux'
set -g @dracula-show-powerline true
set -g @dracula-show-edge-icons false
# Transparent powerline background
set -g @dracula-transparent-powerline-bg true
# the left separator symbol is inversed with a transparent background, you can modify it with any symbol you like
set -g @dracula-inverse-divider 

set -g @dracula-plugins "cpu-usage ram-usage"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

set -g set-clipboard on
