#!/bin/bash

if [ -z "${UTILS_DIR}" ]; then
    echo "UTILS_DIR unset!"
    exit 1
fi

TODOIST_DIR="${UTILS_DIR}/todoist-scripts"
TODOIST_ENV="${UTILS_DIR}/todoist-env"

script=$1
shift

source ${TODOIST_ENV}/bin/activate
python ${TODOIST_DIR}/$script.py "$@"
